# -*- coding: utf-8 -*-
"""diresimulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ou7Q8_ONCF_gsuo7ZmyENYHUS4PW8z0l
"""

# -*- coding: utf-8 -*-
"""
=============================================================================
SISTEMA DE SIMULAÇÃO IMOBILIÁRIA - DIRE RIO
=============================================================================
Aplicação intuitiva para corretores:
- Cadastro de Clientes e Cálculo Automático de Financiamento.
- Consulta de Base de Estoque.
- Simulação de Compra com Cálculo de Pro Soluto (PS).
- Classificação de Risco/Crédito do Cliente.

Baseado no design da V9.6 do Sistema de Portfólios.
=============================================================================
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
from datetime import datetime
import io

# =============================================================================
# 1. CONFIGURAÇÕES E CONSTANTES GLOBAIS
# =============================================================================

# Simulação de carregamento de dados (Baseado nos arquivos enviados)
# Em um cenário real, usaríamos pd.read_csv com os caminhos dos arquivos.
def carregar_dados_mock():
    # Dados de Financiamento (Simplificado para o motor de busca)
    rendas = np.arange(1500, 15000, 100)
    data_finan = {
        'Renda': rendas,
        'F2_Não_Não': rendas * 45, # Faixa 2, Fator Social Não, Cotista Não
        'F2_Sim_Não': rendas * 48,
        'F2_Não_Sim': rendas * 50,
        'F2_Sim_Sim': rendas * 52,
        'F3_Geral': rendas * 40
    }
    df_finan = pd.DataFrame(data_finan)

    # Base de Estoque
    data_estoque = {
        'Identificador': [f'BL{i:02d}-0{j:02d}' for i in range(1, 6) for j in range(1, 5)],
        'Empreendimento': ['Viva Vida Recanto Clube', 'Conquista Oceânica', 'Residencial Jerivá', 'Nova Caxias Up'] * 5,
        'Valor de Venda': np.random.randint(190000, 350000, 20),
        'Status': ['Disponível', 'Disponível', 'Reservado', 'Disponível'] * 5
    }
    df_estoque = pd.DataFrame(data_estoque)

    # Políticas de Pro Soluto
    df_politicas = pd.DataFrame({
        'CLASSIFICAÇÃO': ['EMCASH', 'DIAMANTE', 'OURO', 'PRATA', 'BRONZE', 'AÇO'],
        'MAX_PS': [0.25, 0.25, 0.20, 0.18, 0.15, 0.10],
        'PARCELAS': [66, 84, 84, 84, 80, 60]
    })

    return df_finan, df_estoque, df_politicas

# =============================================================================
# 2. MOTOR DE CÁLCULO IMOBILIÁRIO
# =============================================================================

class MotorCalculoDirecional:
    def __init__(self, df_finan, df_politicas):
        self.df_finan = df_finan
        self.df_politicas = df_politicas

    def calcular_financiamento_aprovado(self, renda, fator_social, cotista_fgts):
        """Busca automática na tabela de financiamento com base na renda."""
        # Encontra a linha de renda mais próxima
        idx = (self.df_finan['Renda'] - renda).abs().idxmin()
        row = self.df_finan.iloc[idx]

        # Lógica de seleção de coluna baseada nas premissas
        coluna = f"F2_{'Sim' if fator_social else 'Não'}_{'Sim' if cotista_fgts else 'Não'}"

        if renda > 4700: # Exemplo de corte para Faixa 3
            valor = row['F3_Geral']
        else:
            valor = row.get(coluna, row['F2_Não_Não'])

        return float(valor)

    def simular_pro_soluto(self, valor_unidade, finan_aprovado, fgts_subsidio, classification):
        """Calcula o GAP (Pro Soluto) e valida contra a política."""
        gap = valor_unidade - finan_aprovado - fgts_subsidio
        politica = self.df_politicas[self.df_politicas['CLASSIFICAÇÃO'] == classification].iloc[0]

        ps_maximo = valor_unidade * politica['MAX_PS']
        excedente = gap - ps_maximo

        return {
            'gap_total': max(0, gap),
            'ps_max_permitido': ps_maximo,
            'excedente_ato': max(0, excedente),
            'parcelas': politica['PARCELAS'],
            'valor_parcela': max(0, gap) / politica['PARCELAS'] if gap > 0 else 0
        }

# =============================================================================
# 3. INTERFACE E DESIGN (MANTENDO O CSS ORIGINAL)
# =============================================================================

def configurar_pagina():
    st.set_page_config(page_title="Simulador de Vendas Direcional", page_icon="🏠", layout="wide")
    st.markdown("""
        <style>
        :root { --primary-color: #d32f2f; --secondary-color: #6c757d; --background-light: #f8f9fa; }
        body, .stApp { font-family: 'Inter', sans-serif; background-color: var(--background-light); }
        .main-header { font-family: 'Inter', sans-serif; color: #111; text-align: center; padding: 2rem 0; font-size: 2.5rem !important; font-weight: 700; }
        .info-box { background-color: #ffffff; border: 1px solid #e0e0e0; padding: 20px; border-radius: 12px; box-shadow: 0 4px 12px rgba(0,0,0,0.05); margin-bottom: 20px; }
        h2, h3 { text-align: center !important; color: #d32f2f; }
        [data-testid="stMetric"] { text-align: center; background-color: #fff; border: 1px solid #eee; border-radius: 10px; padding: 15px; }
        .stTabs [data-baseweb="tab-list"] { justify-content: center; }
        .stButton button { border-radius: 8px; font-weight: 600; width: 100%; }
        </style>
    """, unsafe_allow_html=True)

# =============================================================================
# 4. ABAS DA APLICAÇÃO
# =============================================================================

def aba_estoque(df_estoque):
    st.markdown("## 🏢 Consulta de Estoque Disponível")
    st.markdown('<div class="info-box">Filtre as unidades disponíveis para simulação de venda.</div>', unsafe_allow_html=True)

    col1, col2 = st.columns([1, 3])
    with col1:
        empreendimento = st.multiselect("Filtrar Empreendimento", options=df_estoque['Empreendimento'].unique())
        status = st.checkbox("Apenas Disponíveis", value=True)

    df_filtered = df_estoque.copy()
    if empreendimento:
        df_filtered = df_filtered[df_filtered['Empreendimento'].isin(empreendimento)]
    if status:
        df_filtered = df_filtered[df_filtered['Status'] == 'Disponível']

    with col2:
        st.dataframe(df_filtered, use_container_width=True, hide_index=True)

def aba_simulador(df_finan, df_estoque, df_politicas):
    st.markdown("## ⚙️ Simulador de Compra e Pro Soluto")
    motor = MotorCalculoDirecional(df_finan, df_politicas)

    with st.form("form_simulacao"):
        col1, col2 = st.columns(2)

        with col1:
            st.subheader("Dados do Cliente")
            nome = st.text_input("Nome do Cliente")
            renda = st.number_input("Renda Bruta Familiar (R$)", min_value=1500, value=3500, step=100)
            fgts = st.number_input("Saldo FGTS + Subsídio (R$)", min_value=0, value=0)
            classif = st.selectbox("Classificação do Cliente", options=df_politicas['CLASSIFICAÇÃO'].unique())

        with col2:
            st.subheader("Condições de Financiamento")
            fator_soc = st.checkbox("Possui Fator Social?")
            cotista = st.checkbox("É Cotista FGTS? (3+ anos)")

            # Cálculo automático de financiamento sugerido
            finan_sugerido = motor.calcular_financiamento_aprovado(renda, fator_soc, cotista)
            st.info(f"💰 **Financiamento Estimado:** R$ {finan_sugerido:,.2f}")
            finan_final = st.number_input("Financiamento Aprovado Final (R$)", value=finan_sugerido)

        st.markdown("---")
        st.subheader("Seleção da Unidade")
        unidade_ref = st.selectbox("Escolha a Unidade do Estoque",
                                  options=df_estoque[df_estoque['Status'] == 'Disponível']['Identificador'].unique())

        btn_simular = st.form_submit_button("🚀 Gerar Simulação de Compra")

    if btn_simular:
        unidade_row = df_estoque[df_estoque['Identificador'] == unidade_ref].iloc[0]
        valor_unidade = unidade_row['Valor de Venda']

        res = motor.simular_pro_soluto(valor_unidade, finan_final, fgts, classif)

        st.markdown("### 📊 Resultado da Simulação")
        m1, m2, m3, m4 = st.columns(4)
        m1.metric("Valor da Unidade", f"R$ {valor_unidade:,.2f}")
        m2.metric("GAP (Pro Soluto)", f"R$ {res['gap_total']:,.2f}")
        m3.metric("Entrada (Ato)", f"R$ {res['excedente_ato']:,.2f}")
        m4.metric("Parcelas PS", f"{res['parcelas']}x")

        st.markdown("---")

        # Gráfico de Composição do Pagamento
        labels = ['Financiamento', 'FGTS/Subsídio', 'Pro Soluto']
        values = [finan_final, fgts, res['gap_total']]

        fig = go.Figure(data=[go.Pie(labels=labels, values=values, hole=.4, marker_colors=['#d32f2f', '#424242', '#757575'])])
        fig.update_layout(title="Composição do Pagamento", template="plotly_white")
        st.plotly_chart(fig, use_container_width=True)

        # Detalhamento em tabela
        st.markdown(f"""
        <div class="info-box">
        <strong>Resumo para o Corretor:</strong><br>
        O cliente <b>{nome}</b> possui renda de R$ {renda:,.2f}. <br>
        Para a unidade <b>{unidade_ref}</b> no empreendimento <b>{unidade_row['Empreendimento']}</b>:<br>
        - Valor Parcela Pro Soluto: <b>R$ {res['valor_parcela']:,.2f}</b><br>
        - Status da Política ({classif}): {'✅ DENTRO DA MARGEM' if res['excedente_ato'] == 0 else '⚠️ REQUER ATO COMPLEMENTAR'}
        </div>
        """, unsafe_allow_html=True)

# =============================================================================
# 5. EXECUÇÃO PRINCIPAL
# =============================================================================

def main():
    configurar_pagina()
    st.markdown('<h1 class="main-header">Sistema de Vendas Adaptativo - Dire Rio</h1>', unsafe_allow_html=True)

    # Carregamento dos dados base
    df_finan, df_estoque, df_politicas = carregar_dados_mock()

    tabs = st.tabs(["🏠 Início", "🏢 Base de Estoque", "⚙️ Simulador de Compra", "📖 Políticas"])

    with tabs[0]:
        st.markdown("## Bem-vindo ao Simulador DIRE RIO")
        st.markdown("""
        <div class="info-box" style="text-align: center;">
        <h3>🚀 Agilidade no Fechamento de Vendas</h3>
        <p>Utilize esta ferramenta para calcular automaticamente o enquadramento do seu cliente,
        consultar o estoque em tempo real e gerar simulações de Pro Soluto precisas.</p>
        </div>
        """, unsafe_allow_html=True)

        # Dashboard Simples
        c1, c2, c3 = st.columns(3)
        c1.metric("Unidades Disponíveis", len(df_estoque[df_estoque['Status'] == 'Disponível']))
        c2.metric("Média de Preço", f"R$ {df_estoque['Valor de Venda'].mean():,.2f}")
        c3.metric("Última Atualização", datetime.now().strftime("%d/%m/%Y"))

    with tabs[1]:
        aba_estoque(df_estoque)

    with tabs[2]:
        aba_simulador(df_finan, df_estoque, df_politicas)

    with tabs[3]:
        st.markdown("## 📖 Políticas de Crédito e Pro Soluto")
        st.table(df_politicas)
        st.info("As regras de parcelamento e teto de Pro Soluto são baseadas na classificação de risco do cliente.")

if __name__ == "__main__":
    main()